---
- name: Running PMM Data Container without Security ( unprotected )
  docker_container:
    name: pmm-server
    insecure_registry: true
    image: "percona/pmm-server:{{ pmm_server_version }}"
    state: started
    cpuset_cpus: "{{ pmm_server_docker_cpuset_cpus }}"
    memory: "{{ pmm_server_docker_memory }}"
    memory_reservation: "{{ pmm_server_docker_memory_reservation }}"
    purge_networks: "{{ pmm_server_docker_purge_networks }}"
    networks: "{{ pmm_server_docker_networks }}"
    volumes:
    - /etc/grafana:/etc/grafana
    volumes_from:
    - pmm-data
    env: "{{ __pmm_server_env }}"
    ports:
    - "80:80"
    restart_policy: always
