---
- name: Creating PMM Data Container
  docker_container:
    name: pmm-data
    image: "percona/pmm-server:{{ pmm_server_version }}"
    state: present
    volumes: "{{ __pmm_server_docker_data_volumes }}"
    command: /bin/true
