---

# Check if docker is installed
- include_tasks: docker-check.yml

# Uninstall pmm-server by removing PMM Data Container
- include_tasks: uninstall-pmm-container.yml
  when: pmm_server_UNINSTALL_PMM

# Variable Configuration
- include_tasks: variables.yml
- include_tasks: sanity-check.yml

# Create PMM Data Container
- include_tasks: create-pmm-container.yml
  when: not pmm_server_UNINSTALL_PMM

# Run PMM Data Container in insecure mode
- include_tasks: container-basic.yml
  when: 
    - not pmm_server_ENABLE_PROTECTION
    - not pmm_server_ENABLE_SSL
    - not pmm_server_UNINSTALL_PMM

# Run PMM Data Container with userid and password protection
- include_tasks: container-protected.yml
  when:
    - pmm_server_ENABLE_PROTECTION
    - not pmm_server_ENABLE_SSL
    - not pmm_server_UNINSTALL_PMM

# Run PMM Data Container with SSL Enryption only or combined with password protection
- include_tasks: container-ssl-combined.yml
  when: not pmm_server_UNINSTALL_PMM
